version: '3'
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-github-actions-demo
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - docker-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: Demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - docker-network

  # Add this Newman service to your Docker Compose
  newman:
    image: postman/newman:latest
    volumes:
      - .:/etc/newman
    networks:
      - docker-network
    depends_on:
      - demo
    command: >
      run /etc/newman/postman_collection.json 
      -e /etc/newman/postman_environment.json 
      --reporters cli,json 
      --reporter-json-export /etc/newman/newman-report.json

networks:
  docker-network:
    driver: bridge

volumes:
  pgdata: