version: '3.8'

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-github-actions-demo
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - docker-network
      - host-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: Demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - docker-network
      - host-network

networks:
  docker-network:
    driver: bridge
  host-network:
    driver: host

volumes:
  pgdata: