name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t demo-postman-tests .

      - name: Run Newman Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/results:/etc/newman/results \
            demo-postman-tests \
            --reporters cli,json \
            --reporter-json-export /etc/newman/results/newman-report.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-results
          path: results/newman-report.json
