name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Check out the code from the repository

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew  # Give permission to the Gradle wrapper

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4  # Set up Gradle

    - name: Run Gradle Build
      run: ./gradlew build  # Build the project

    # Build the Docker image and run the container
    - name: Build Docker Image
      run: docker build -t demo-app .  # Build the Docker image

    - name: Run Docker Container
      run: docker run -d -p 8080:8080 --name demo-app-container demo-app  # Run the Docker container

    # Clean up after the test
    - name: Clean up Docker Container
      run: docker rm -f demo-app-container  # Remove the Docker container after tests
