name: Automated functional testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and Test with Gradle
      run: ./gradlew build

    - name : Build the Docker Image
      run : docker build . --file Dockerfile --tag demo-app

    - name : Creating docker network
      run : docker network create docker-network

    - name : Docker Compose Up
      run : docker compose up -d

    - name : Pull Newman Docker Image
      run : docker pull postman/newman:latest

    - name : Run Tests using Newman
      uses: postman/newman-action@v1.1.0
      with:
        collection: './postman_collection.json'
        environment: './postman_environment.json'
        reporters: 'cli,junit'
        reporter-junit-export: 'newman-{{runTestSummary.timestamp}}.xml'

    - name: Publish Test Results to GitHub Packages
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: newman-*.xml

    - name : Docker Compose Down
      run : docker compose down
